=== sturcotte06/sporacid-gcs/src/gcs.webapp.utils/src/resources/xml-schemas/gcs.menu.schema.dtd
<!ELEMENT application-menu (menu-entry*)>
	<!ATTLIST application-menu for CDATA #REQUIRED>
	<!ELEMENT menu-entry (sub-menu?)>
		<!ATTLIST menu-entry name CDATA #REQUIRED>
		<!ATTLIST menu-entry path CDATA "">
		<!ATTLIST menu-entry load-async (true | false) "true">
		<!ELEMENT sub-menu (sub-menu-entry*)>
			<!ELEMENT sub-menu-entry EMPTY>
				<!ATTLIST sub-menu-entry name CDATA #REQUIRED>
				<!ATTLIST sub-menu-entry path CDATA #REQUIRED>
				<!ATTLIST sub-menu-entry load-async (true | false) "true">

=== sturcotte06/sporacid-gcs/src/gcs.website/src/resources/gcs.website.menu.membre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application-menu SYSTEM "xml-schemas\gcs.menu.schema.dtd">

<application-menu for="membre">
  <menu-entry name="application_menu_members">
    <sub-menu>
      <sub-menu-entry name="application_menu_view_members" path="/membres/gerer" />
    </sub-menu>
  </menu-entry>
  <menu-entry name="application_menu_inventory">
    <sub-menu>
      <sub-menu-entry name="application_menu_view_iventory" path="/inventaire/gerer" />
    </sub-menu>
  </menu-entry>
  <menu-entry name="application_menu_suppliers">
    <sub-menu>
      <sub-menu-entry name="application_menu_view_suppliers" path="/fournisseurs/gerer" />
    </sub-menu>
  </menu-entry>
  <menu-entry name="application_menu_sponsors">
    <sub-menu>
      <sub-menu-entry name="application_menu_view_sponsors" path="/commandites/gerer" />
    </sub-menu>
  </menu-entry>
  <menu-entry name="application_menu_help" path="/aide" />
</application-menu>
