=== sturcotte06/sporacid-gcs/src/gcs.webapp.utils.tests/src/resources/xml-schemas/application_message.schema.dtd
<!ELEMENT application-messages (message*)>
	<!ATTLIST application-messages locale CDATA #REQUIRED>
	<!ELEMENT message EMPTY>
		<!ATTLIST message key ID #REQUIRED>
		<!ATTLIST message message CDATA #REQUIRED>
		<!ATTLIST message description CDATA "">

=== sturcotte06/sporacid-gcs/src/gcs.webservices/src/resources/gcs.webservices.application_messages.fr-ca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application-messages SYSTEM "xml-schemas\application_message.schema.dtd">

<application-messages locale="fr-ca">
  <!-- Ldap authentication messages -->
  
  <!-- Authentication service messages -->
  <message key="authentication_login_success" message="L'authentification a été effectuée avec succès." />
  <message key="authentication_login_invalid_request" message="La requête d'authentification est malformée." />
  <message key="authentication_login_wrong_username" message="Le nom d'usager est invalide." />
  <message key="authentication_login_wrong_password" message="Le mot de passe est invalide." />
  <message key="authentication_logout_success" message="La déconnexion a été effectuée avec succès." />
  <message key="authentication_logout_invalid_request" message="La requête de déconnexion est malformée." />
  <!-- Members service messages -->
  <message key="members_get_member_successful" message="L'obtention du membre a été effectué avec succès." />
  <message key="members_get_member_invalid_request" message="La requête d'obtention d'un membre est malformée." />
  <!-- General messages -->
  <message key="security_authentication_required" message="L'authentification est nécessaire pour cette opération." />
  <message key="security_denied_access" message="L'usager n'a pas les droits." />
</application-messages>

=== sturcotte06/sporacid-gcs/src/gcs.website/src/resources/gcs.website.application_messages.fr-ca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application-messages SYSTEM "xml-schemas\application_message.schema.dtd">

<application-messages locale="fr-ca">
  <!-- Validation messages -->
  <message key="validation_authentication_username_bad_length" message="Le nom d'usager doit être entre 1 et 10 caractères." />
  <message key="validation_authentication_password_empty" message="Le mot de passe ne peut être vide." />
  
  <!-- Application menu messages -->
  <message key="application_menu_members" message="Membres" />
  <message key="application_menu_view_members" message="Visionner les membres" />
  <message key="application_menu_manage_members" message="Gestion des membres" />
  <message key="application_menu_add_member" message="Ajouter un membre" />
  <message key="application_menu_manage_trainings" message="Gestion des formations" />
  <message key="application_menu_inventory" message="Inventaire" />
  <message key="application_menu_view_iventory" message="Visionner l'inventaire" />
  <message key="application_menu_manage_iventory" message="Gestion de l'inventaire" />
  <message key="application_menu_add_inventory_item" message="Ajouter un item" />
  <message key="application_menu_suppliers" message="Fournisseurs" />
  <message key="application_menu_view_suppliers" message="Visonner les fournisseurs" />
  <message key="application_menu_manage_suppliers" message="Gestion des fournisseurs" />
  <message key="application_menu_add_supplier" message="Ajouter un fournisseur" />
  <message key="application_menu_sponsors" message="Commandites" />
  <message key="application_menu_view_sponsors" message="Visionner les commandites" />
  <message key="application_menu_manage_sponsors" message="Gestion des commandites" />
  <message key="application_menu_add_sponsor" message="Ajouter une commandite" />
  <message key="application_menu_help" message="Aide" />
</application-messages>
