=== sturcotte06/sporacid-gcs/src/gcs.webservices/src/resources/xml-schemas/application_security.schema.dtd
<!ELEMENT application-security (application-module*)>
	<!ELEMENT application-module (application-role*)>
		<!ATTLIST application-module name ID #REQUIRED>
		<!ELEMENT application-role (role-right*)>
			<!ATTLIST application-role name CDATA #REQUIRED>
				<!ELEMENT role-right EMPTY>
					<!ATTLIST role-right operation (Create | Read | Update | Delete) #REQUIRED>

=== sturcotte06/sporacid-gcs/src/gcs.webservices/src/resources/gcs.webservices.application_security.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application-messages SYSTEM "xml-schemas\application_security.schema.dtd">

<application-security>
  <!-- Members module definition -->
  <application-module name="members_module">
    <application-role name="capitaine">
      <role-right operation="Create" />
      <role-right operation="Read" />
      <role-right operation="Update" />
      <role-right operation="Delete" />
    </application-role>
    <application-role name="membre">
      <role-right operation="Read" />
    </application-role>
  </application-module>
  
  <!-- Inventory module definition -->
  <application-module name="inventory_module">
    <application-role name="capitaine">
      <role-right operation="Create" />
      <role-right operation="Read" />
      <role-right operation="Update" />
      <role-right operation="Delete" />
    </application-role>
    <application-role name="membre">
      <role-right operation="Read" />
    </application-role>
  </application-module>
  
  <!-- Suppliers module definition -->
  <application-module name="suppliers_module">
    <application-role name="capitaine">
      <role-right operation="Create" />
      <role-right operation="Read" />
      <role-right operation="Update" />
      <role-right operation="Delete" />
    </application-role>
    <application-role name="membre">
      <role-right operation="Read" />
    </application-role>
  </application-module>
  
  <!-- Sponsors module definition -->
  <application-module name="sponsors_module">
    <application-role name="capitaine">
      <role-right operation="Create" />
      <role-right operation="Read" />
      <role-right operation="Update" />
      <role-right operation="Delete" />
    </application-role>
    <application-role name="membre">
      <role-right operation="Read" />
    </application-role>
  </application-module>
</application-security>
